### ISSUE TITLE
Increase diversity - Crowding

### ISSUE THREAD

**Issue by olavforland** [olavforland/IT3708#42]
Currently, the population rapidly converges to one common solution. Therefore, we need to increase diversity.

### Requirements
- [ ] Instead of the fitness-based children (and parent) selection criteria, implement crowding (this can be done in the binary tournament between parents or between parents and children).
- [ ] Test where (and how) it is best to implement crowding

### Dependencies
- [x] #45

**Comment by jke007** [comment]
Made a new parent selection function which simply selects p1, p2 = argmin(similarity). Did not have great results.
