### ISSUE TITLE
Chromosome struct

### ISSUE THREAD

**Issue by olavforland** [olavforland/IT3708#48]
Create chromosome struct similar to what done in Project 2

- [x] Genotype
- [ ] Phenotype
- [x] Graph representation - is this needed?
- [ ] Fitness

**Comment by jke007** [comment]
Made Chromosome struct, and initial MST which can be put in graph. Currently MST is a directed graph where parent-nodes are keys and children are values in a dictionary. Translates to genotype by comparing if child nodes are below, left, right or above parent node. Updating graph should be simple, by only moving the child to another key if it is mutated.
